Repository yju-FukuFuku/FukuFuku_Backend_Refactoring-repo, pull requests merged in 2023-10, with the labels that each got.

#24 feat: Implement pagination
  src/boards/board.repository.ts
  src/boards/boards.controller.ts
  src/boards/boards.service.ts
  src/boards/dto/search-board.dto.ts
  src/user/user.controller.ts
  src/user/user.repository.ts
  src/user/user.service.ts
Labels: feat

#25 fix(prisma): Fix schema.prisma to update nickName fields
  prisma/schema.prisma
Labels: feat

#26 refactor: Refactor createUser method to use email as default nickName
  src/boards/dto/create-board.dto.ts
  src/common/guard/access.guard.ts
  src/user/user.repository.ts
Labels: 🐞 BugFix, 🔨 Refactor

#29 글 생성 태그 관련 수정
  package-lock.json
  prisma/schema.prisma
  src/boards/board.repository.ts
  src/boards/boards.controller.ts
  src/boards/boards.service.ts
  src/boards/dto/create-board.dto.ts
  src/boards/dto/update-board.dto.ts
  src/replys/replys.controller.ts
  src/tags/dto/tag.dto.ts
  src/tags/tag.repository.ts
  src/tags/tags.controller.ts
Labels: ✨ Feature

#28 feat(auth): add verifyUser endpoint
  src/auth/auth.controller.ts
Labels: ✨ Feature

#30 feat: Implement pagination using lastId
  .prettierrc
  prisma/migrations/20231015092713_alter_user_table_and_alter_board_table/migration.sql
  prisma/migrations/20231015092825_alter_user_table/migration.sql
  prisma/migrations/20231015093000_alter_comment_table_and_alter_reply_table/migration.sql
  prisma/migrations/20231015094645_alter_image_table/migration.sql
  prisma/migrations/20231015101708_alter_user_table/migration.sql
  prisma/migrations/20231015130430_create_user_image_table/migration.sql
  prisma/schema.prisma
  src/boards/board.repository.ts
  src/boards/boardImage.repository.ts
  src/boards/boards.controller.ts
  src/boards/boards.service.ts
  src/boards/dto/create-board.dto.ts
  src/boards/dto/search-board.dto.ts
  src/upload/upload.controller.ts
  src/upload/upload.repository.ts
  src/upload/upload.service.ts
  src/user/user.module.ts
  src/user/user.repository.ts
  src/user/user.service.ts
  src/user/userImage.repository.ts
Labels: ✨ Feature

#31 fix(board.repository): Fix cursor value in findMany method
  src/boards/board.repository.ts
Labels: 🐞 BugFix

#32 FukuFuku refactoring
  .prettierrc
  docker-compose.db.yml
  package-lock.json
  package.json
  prisma/migrations/20231015092713_alter_user_table_and_alter_board_table/migration.sql
  prisma/migrations/20231015092825_alter_user_table/migration.sql
  prisma/migrations/20231015093000_alter_comment_table_and_alter_reply_table/migration.sql
  prisma/migrations/20231015094645_alter_image_table/migration.sql
  prisma/migrations/20231015101708_alter_user_table/migration.sql
  prisma/migrations/20231015130430_create_user_image_table/migration.sql
  prisma/schema.prisma
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/g-oauth/g-oauth.service.ts
  src/auth/g-oauth/g-oauth.strategy.ts
  src/boards/board.repository.ts
  src/boards/boardImage.repository.ts
  src/boards/boards.controller.ts
  src/boards/boards.service.ts
  src/boards/dto/create-board.dto.ts
  src/boards/dto/search-board.dto.ts
  src/boards/dto/update-board.dto.ts
  src/common/guard/access.guard.ts
  src/common/guard/refresh.guard.ts
  src/replys/replys.controller.ts
  src/tags/dto/tag.dto.ts
  src/tags/tag.repository.ts
  src/tags/tags.controller.ts
  src/upload/upload.controller.ts
  src/upload/upload.repository.ts
  src/upload/upload.service.ts
  src/user/dto/create-user.dto.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.repository.ts
  src/user/user.service.ts
  src/user/userImage.repository.ts
Labels: ✨ Feature
